import About from '@/components/About'
import Navbar from '@/components/Navbar'
import Skills from '@/components/Skills'
import Head from 'next/head'
import { useEffect } from 'react'
import React from 'react';
import Projects from '@/components/Projects'


export default function Home() {

  useEffect(()=>{
// i add here: <HTMLElement>  to remove the red line under 'style'
    let path = document.querySelector('path.pathLine') as SVGGeometryElement;

    if(path != undefined){
      let pathLength = path.getTotalLength();
      
      path.style.strokeDasharray = pathLength + " " + pathLength;
      path.style.strokeDashoffset = "2530"; //"2530"

      window.addEventListener('scroll', () => {
        // how much we scroll down by %
          let scrollPercentage = ((document.documentElement.scrollTop + document.body.scrollTop) / (document.documentElement.scrollHeight - document.documentElement.clientHeight)+ 0.10); //+ 0.25
          

        // length to offset the dashes
          let drawLength = pathLength * (scrollPercentage);
          
        // draw in reverse
          path!.style.strokeDashoffset = ((pathLength - drawLength)-200).toString(); //- 200
          
          if((((pathLength - drawLength)-200) > 2780) ){
              path!.style.strokeDashoffset = ((pathLength - drawLength)-460).toString()
          }

      });
    }
  },[])
  

  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
      <div className='h-[10vh] sticky top-0 z-[1500]'>
        <Navbar />
      </div>

      <div className="svgAnimeResp absolute top-[3%] left-[50.5%] translate-x-[-48%] h-[305%] text-center overflow-hidden z-[100]">

        <svg className='inline-block h-full' viewBox="0 0 127 1842" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path className='pathLine' d="M62.5 -9V104.5V256C62.5 273 58.266 291.355 47.5002 302H18C5.5 302 3.5 301.5 3.5 315V335.25V366.5C3.65431 383.755 7.50001 381 18 381C28.5 381 24.5 383.5 24.5 364.5C24.5 345.5 41.6888 350.315 37.5 349.75C33.3112 349.185 33 337.701 33 337.701C33 337.701 31.3661 319.256 47.5002 319.605C63.6343 319.955 61.5 337.701 61.5 337.701C61.5 337.701 58.862 348.72 56.5004 349.75C54.1388 350.78 70.9804 344.059 71 364.5C71.0195 384.941 67 381 75.0003 381C83.0006 381 95.0002 381 95.0002 381C107.552 380.4 115.352 383.583 116 366.5V341V315C116.446 300.817 112.755 302.631 99.0004 302C99.0004 302 99.0004 302 81.5004 302C64.0004 302 62.5 505.5 62.5 505.5V810V846C62.5 846 56.6789 862.762 50.0004 870L45 863.5L29.5 870L30.5 879L24 884L19.5004 891H10L3.5 907L10 912V920.5L11.5 929L4.99999 935.5L11.5 951.5L20.5 950.5L25.5 957.5L32.5 962V971.5L48 977.5L53.5 970L62 971.5L70.5 970L76.5 976L91.5 970V960L98 955.5L103 948.5H112.5L118 934L111 927L112.5 919L111 910.5L118 904L111 889.5H100.5L96 883L89 878V868.5L74 862L68.5 870H62C62 870 63.9005 1012.5 63.5 1133V1344L64.5 1490.5L50 1470.5H10.5C3.99999 1470.5 3.75516 1471.03 3.99999 1486V1561C4.69051 1573.5 6.94758 1576.04 18.5 1576L64.5 1575.84L111 1576C120.5 1576 124.183 1574.62 124 1561V1513.5C123.984 1502.39 121.772 1498.36 111 1498L3.99999 1500L3.75003 1563.5C3.75003 1574.5 3.49999 1575.84 13.5 1575.84H63.5V1687V1817C60.4457 1813.87 58.5422 1812.69 54.5 1812.5C49.9892 1812.29 47.5 1816.59 47.5 1820.5C47.5 1829 55.151 1832.27 63.5 1838.5C72.2421 1832.83 80.5 1829 80.5 1820.5C80.1406 1816.57 79 1813.5 75 1812.5C68.5 1812.5 66.3322 1814.15 63.5 1819.5" stroke="#373737" strokeWidth="4"/>
        </svg>

      </div>
      
      <div className='h-[90vh] w-full'>
        <video autoPlay loop muted poster='true' className="w-screen h-full absolute object-cover z-[-1]">
                <source src="/videoBG.mp4" type="video/mp4"/>
        </video>

        <About />
      </div>
    
      <div className='h-[100vh] w-screen bg-skillsBG bg-cover border-t-8 border-[#29243ebf]'>
        <Skills/>
      </div>
     {/* continue here change background for projects to be a different picture ! good morning !!! :) */}
      <div className='h-[100vh] w-screen bg-projectsBG bg-cover border-t-8 border-[#29243ebf]'>
        <Projects/>
      </div>
    
    </>
  )
}
